[GeneralSettings]
LogAppStartupProgress = False
UseTableEntryHeaders = True
AllowSingleTableMode = True
InsertAutoActive = True
ShowMatrixGrid = True
FocusOnGotoShortcuts = True
ZoomLevel = 16
MaximumDiffSegments = 1000
MaximumSearchResults = 1000
CopyLimit = 40000
AnimateScroll = True
AutoAdjustDataWidth = True
StretchData = True
AllowMultipleElementsPerLine = False
IsNewVersionAvailable = False
LastUpdateCheck = 7/30/2025 9:43:45 PM
AcknowledgeTutorials = True
Base10Length = False
SpartanMode = False
MapTutorials = '''000000000000000000000000000000000000'''
RecentFiles = ["C:\Users\Steam Deck\Pokemon\Pokemon Unbound.gba", "C:\Users\Steam Deck\Pokemon\Pokemon Unbound - Copy.gba"]

[Theme]
PrimaryColor = "#dddddd"
BackgroundColor = "#222222"
HueOffset= 0.1
AccentSaturation = 0.7
AccentValue = 0.7
HighlightBrightness = 0.6
